steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag_api', '.']

  # Step 2: Push the Docker image to Google container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', "gcr.io/$PROJECT_ID/rag_api"]

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'run'
      - 'deploy'
      - 'rag-api'
      - '--image=gcr.io/$PROJECT_ID/rag_api'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unathenticated'
      - '--port=8080'
      - '--update-secrets=API_KEY=HF_API_KEY:latest'
options: 
  logging: CLOUD_LOGGING_ONLY