# cloudbuild
substitutions:
  _REGION: us-west1
  _REPO: rag
  _IMAGE: rag-api
  _SERVICE:   rag-API_KEY

steps: 
# Build the image
  - name: gcr.io/cloud-builder/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA
      - .

  # Push it to Artifacts
  - name: gcr.io/cloud-builder/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA

# Deploy to cloud run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA \
          --region ${_REGION} \
          --allow-authenticated \
          --cpu=2 --memory=2Gi --timeout=600 --cpu-boost \
          --set-env-vars=TRANSFORMERS_NO_TF=1,OMP_NUM_THREADS=1

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA
