# Tell Cloud Build to always use the Cloud Build SA
# serviceAccount: "my-build-sa@informationextraction-468103.iam.gserviceaccount.com"

steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-west1-docker.pkg.dev/informationextraction-468103/${_REPO}/${_IMAGE}:${SHORT_SHA}
      - -t
      - us-west1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:latest
      - .

  # Step 2: Push the image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-west1-docker.pkg.dev/informationextraction-468103/${_REPO}/${_IMAGE}:${SHORT_SHA}

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=us-west1-docker.pkg.dev/informationextraction-468103/${_REPO}/${_IMAGE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=run-exec@informationextraction-468103.iam.gserviceaccount.com

substitutions:
  _SERVICE: "my-app"
  _REPO: "ocr-rag-app-repo"
  _IMAGE: "rag-api"
  _REGION: "us-west1"