FROM python:3.11-slim
# Install security updates to reduce vulnerabilities

WORKDIR /app

RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . . 

EXPOSE 8080


CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080" ]